### ISSUE TITLE
메인 페이지에서 가져올 수 있는 멤버 객체 개수 제한 관련

### ISSUE THREAD

**Issue by changhwan77** [Tuti-Project/Tuti-Server#11]
## 💡 작업 내용
스크롤이 화면의 끝에 닿을때 마다 새로운 멤버 객체를 담은 프로필 카드 생성
<br>

## 📝 상세 내용
![image](https://github.com/Tuti-Project/Tuti-Server/assets/110464205/11046030-156c-4d67-8a66-81fe6ba47dae)

위 화면은 메인 화면에 진입 시 서버에 멤버 객체를 받아오는 로직을 담은 코드에요.
현재 서버에 요청해서 불러올 수 있는 멤버 객체의 개수가 10개로 제한되어 있는건지 궁금합니다!

- [ ] todo
- [ ] todo
- [ ] todo

<br>

## ✏️ 참고 사항

<br>

**Comment by dlwjddn123** [comment]
메인 페이지에 반환하는 멤버들은 페이징 처리해서 10개씩 보내고 있어요!
```json
  "code": 200,
  "status": "OK",
  "message": "요청에 성공하였습니다.",
  "data": "{ ... }",
  "hasNext" : "true"
```
응답 값에 hasNext가 true이면 다음 페이지를 호출하면 됩니다.

디폴트 값이 0이라 다음 페이지 부르시려면 `/home?page=1` 이렇게 호출하시면 될 거 같습니다!

**Comment by changhwan77** [comment]
감사합니다 👍 !!

**Comment by changhwan77** [comment]
1. 배경:
- 현재 1페이지에 6개의 멤버 객체가 있는데 유저가 스크롤의 끝에 닿이는 순간 한 번 더 1페이지에 쿼리가 가고 이 경우에 hasNext가 false이므로 1페이지에 있는 객체를 불러와 중복된 프로필 카드를 생성하고 있는 문제가 있어요. 

![image](https://github.com/Tuti-Project/Tuti-Server/assets/110464205/e19c4df4-ef7e-4796-8141-fc56ce3e0c69)

2. 질문
- 이를 해결하기 위해 프론트에서 처리해야할 지 서버에서 처리해야 할지에 대해 갈피가 안잡혀 이렇게 질문 남깁니다 :)

**Comment by dlwjddn123** [comment]
hasNext가 false임에도 다시 요청을 보내는 이유가 뭘까요!?

**Comment by changhwan77** [comment]
> hasNext가 false임에도 다시 요청을 보내는 이유가 뭘까요!?

1페이지 내에 이전 쿼리 이외에 추가된 멤버 객체가 있을 수 있기 때문이었어요!

**Comment by changhwan77** [comment]
> > hasNext가 false임에도 다시 요청을 보내는 이유가 뭘까요!?
> 
> 1페이지 내에 이전 쿼리에서 받아온 멤버 이외에  추가된 멤버 객체가 있을 수 있기 때문이었어요!

**Comment by dlwjddn123** [comment]
추가된 멤버 객체라 함은 정확히 어떤걸 의미하나요??

제가 이해하고 있는 로직은
1. 처음 요청(page 0) -> 멤버 객체 10개 반환 및 hasNext=true 반환

2. hasNext=true임을 확인하고 다음 페이지 요청 후 멤버 객체 6개 반환 및 hasNext=false 반환

3. hasNext=false 이므로 호출 종료
 
이렇게인데 추가된 멤버는 어디 부분을 말하시는걸까요?

**Comment by changhwan77** [comment]
정우님이 말씀하신 2번에서 객체 6개 반환 및 호출 종료 후

case ) 유저가 화면에서 다시 스크롤 끝에 닿는 경우
- 서버에 쿼리(page 1) 요청 후 false 반환으로 다음 페이지로 안넘어가는 것이지
- page 1에서 비동기로 7~9번째 멤버 객체가 추가된 경우(다른 유저가 회원가입 함) 이를 받아올 수 있어야 되는 것 아닌지 궁금합니다!

**Comment by dlwjddn123** [comment]
이해했습니다! 서버쪽에서 수정을 해야겠네요!! 
무한 스크롤 방식이 처음이여서 제가 잘 몰랐네요😅😅 마지막 멤버 객체의 아이디 값으로 호출하시면 그 이후의 멤버 객체만 반환하도록 수정해놓겠습니다! 
알바가 12시에 끝나서 내일 오전중으로 해놓을게요!

**Comment by changhwan77** [comment]
아닙니다 👍 👍  저도 처음이라 모르는 부분이 많은데 도와주셔서 감사합니다!!

알바 화이팅입니닷

**Comment by changhwan77** [comment]
[ 02- 06 Api 수정 관련 질문 ] 
![image](https://github.com/Tuti-Project/Tuti-Server/assets/110464205/51a4c59c-2c80-4b02-8a47-0d7af601a8cf)

1. 쿼리 파라미터인 page는 작동하지 않는 건가요? 
2. page0에서 last=5일 경우 6 ~ 10이 불러와져야 하는데 다음과 같이 2, 3, 4만 불러와져요!

![image](https://github.com/Tuti-Project/Tuti-Server/assets/110464205/1767e541-fa1c-465d-a3f6-652eb0ead080)

제가 잘못 알고 있는게 무엇인지 궁금합니다아

**Comment by dlwjddn123** [comment]
아 page 쿼리 파라미터는 없어졌고 last로만 동작하도록 했습니다! 쓸일이 아마 없을거 같아서요.

그리고 멤버가 id 역순으로 되어있어서 last=5 이면 5보다 작은(다음에 있는) 값이 나오게 됩니다!

**Comment by changhwan77** [comment]
헉 혹시 로직을 어떻게 생각하셨는지 여쭤봐도 될까요?!

**Comment by dlwjddn123** [comment]
스크롤 내릴때마다 불러왔던 마지막 멤버id를 기준으로 최대10개 가져오도록 했습니다! 

맨처음 호출할때는 가장 큰 멤버 id부터 10개 가져오고, 그 이후 호출부터는 마지막 멤버 id 보다 작은 id 값을 가진 멤버를 가져오도록요

**Comment by changhwan77** [comment]
1) 10개씩만 가져올 수 있도록 제한(호출할 수 있는 데이터가 10개 미만이면 작동 X)
2) 가장 큰 멤버 id 부터 역순으로 가져옴.
3) 마지막 멤버 ID를 호출하면(예를 들어 12) 11 ~ 3까지 10개씩 들고옴.

이렇게 정리되는 거군요!

그렇게 반영해서 수정하고 PR 할게요~!

**Comment by dlwjddn123** [comment]
1번에서 10개 미만이여도 동작합니다!
다만 hasnext가 false라 다음에 불러올 데이터는 없죠

**Comment by changhwan77** [comment]
오우 좋습니다! 해결했네요 ~~!
