### ISSUE TITLE
스웨거 접속 오류

### ISSUE THREAD

**Issue by changhwan77** [Tuti-Project/Tuti-Server#12]
## 💡 작업 내용
API 호출을 통해 실험해보려고 하는데 서버 접속이 안되는 오류가 있어요! 

<br>

## 📝 상세 내용

![image](https://github.com/Tuti-Project/Tuti-Server/assets/110464205/5d26eb20-8b99-4b8d-b6c2-42613535000f)

현재 어떤 문제가 있어서 접속이 안되는지 궁금합니다!

- [ ] todo
- [ ] todo
- [ ] todo

<br>

## ✏️ 참고 사항

<br>

**Comment by dlwjddn123** [comment]
죄송해요 ㅠㅠ CI/CD 구축하느라 서버 꺼진 걸 미리 말씀을 못드렸네요
